# -*- coding: utf-8 -*-
"""ProdutoConsumidor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18efrX91VhPjiCayv3tc6I0d_GamFVSST
"""

import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('data.txt', sep = ";")

dataset.columns = ['NumSerie', 'ID', 'Tloja_prod', 'Fab_consumo', 'Fab_prod', 'Transp_consumo']

dataset.head

dataset['Producao'] = pd.Series(dataset['Fab_consumo'] -dataset['Tloja_prod'], index=dataset.index)

dataset['Entrega'] = pd.Series(dataset['Transp_consumo'] -dataset['Fab_prod'], index=dataset.index)

plt.subplot(1, 2, 1)
plt.plot(dataset['Producao'])
plt.title('Producao')

plt.subplot(1, 2, 2)
plt.plot(dataset['Entrega'])
plt.title('Entrega')
plt.tight_layout()
plt.show()

